"""added models

Revision ID: bc0ece2f650d
Revises: 
Create Date: 2025-03-10 10:50:30.075963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc0ece2f650d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coords',
    sa.Column('id', sa.Integer(), nullable=False, comment='Идентификатор'),
    sa.Column('latitude', sa.Float(), nullable=False, comment='Широта'),
    sa.Column('longitude', sa.Float(), nullable=False, comment='Долгота'),
    sa.Column('height', sa.Integer(), nullable=False, comment='Высота'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False, comment='Идентификатор'),
    sa.Column('data', sa.String(), nullable=False, comment='Изображение'),
    sa.Column('title', sa.String(), nullable=False, comment='Название'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('levels',
    sa.Column('id', sa.Integer(), nullable=False, comment='Идентификатор'),
    sa.Column('winter', sa.Enum('A1', 'A2', 'A3', 'B1', 'B2', 'B3', 'NC', name='levelpereval'), nullable=False, comment='Зимнее время'),
    sa.Column('summer', sa.Enum('A1', 'A2', 'A3', 'B1', 'B2', 'B3', 'NC', name='levelpereval'), nullable=False, comment='Летнее время'),
    sa.Column('spring', sa.Enum('A1', 'A2', 'A3', 'B1', 'B2', 'B3', 'NC', name='levelpereval'), nullable=False, comment='Весеннее время'),
    sa.Column('autumn', sa.Enum('A1', 'A2', 'A3', 'B1', 'B2', 'B3', 'NC', name='levelpereval'), nullable=False, comment='Осеннее время'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False, comment='Идентификатор'),
    sa.Column('fam', sa.String(), nullable=False, comment='Фамилия'),
    sa.Column('name', sa.String(), nullable=False, comment='Имя'),
    sa.Column('otc', sa.String(), nullable=False, comment='Отчество'),
    sa.Column('email', sa.String(), nullable=False, comment='Почта'),
    sa.Column('phone', sa.String(), nullable=False, comment='Телефон'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('perevals',
    sa.Column('id', sa.Integer(), nullable=False, comment='Идентификатор'),
    sa.Column('beauty_title', sa.String(), nullable=False, comment='Короткое название'),
    sa.Column('title', sa.String(), nullable=False, comment='Название'),
    sa.Column('other_title', sa.String(), nullable=False, comment='Альтернативное название'),
    sa.Column('connect', sa.String(), nullable=True, comment='Что соединяет перевал'),
    sa.Column('add_time', sa.DateTime(), nullable=False, comment='Время отправки'),
    sa.Column('status', sa.Enum('NEW', 'PEN', 'ACC', 'REJ', name='statuspereval'), nullable=True, comment='Статус модерации'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='Идентификатор пользователя'),
    sa.Column('coord_id', sa.Integer(), nullable=False, comment='Идентификатор координат'),
    sa.Column('level_id', sa.Integer(), nullable=False, comment='Идентификатор уровней'),
    sa.ForeignKeyConstraint(['coord_id'], ['coords.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['level_id'], ['levels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('images_pereval',
    sa.Column('id', sa.Integer(), nullable=False, comment='Идентификатор'),
    sa.Column('pereval_id', sa.Integer(), nullable=False, comment='Идентификатор перевала'),
    sa.Column('image_id', sa.Integer(), nullable=False, comment='Идентификатор изображения'),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pereval_id'], ['perevals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('images_pereval')
    op.drop_table('perevals')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('levels')
    op.drop_table('images')
    op.drop_table('coords')
    # ### end Alembic commands ###
